### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by ZackaryEijbersen** [haomateach/info1112#1]
100418273
Hello I have a question, regarding the development environment. Can you please specify if we need to download both Visual studio , and Codelite or just one. Also if we need to download Visual Studio which version should we download.(there is three)
Thank you

**Comment by haomateach** [comment]
Thanks for posting the first issue :)

Ans to Q1: Just one of VS and Codelite is OK. 
Ans to Q2: Community edition is good enough, and I believe the other two editions are not free.

**Comment by keiichilam** [comment]
100424375, Keith Lam
I suppose Students like us are entitled to use the CLION Free Educational Licenses
https://www.jetbrains.com/community/education/#students

Just wonder if CLION has any advantage from CodeLite? 
of course, it would be easier to prevent issues by following the customization of codelite as in the videos

**Comment by haomateach** [comment]
@keiichilam There are certainly other IDEs over there, but there is a reason why we want to limit our IDE options for class so that we won't run into too many setup issues. Codelite or Visual Studio is preferred.
