### ISSUE TITLE
Coding workspace (Browser or pc)

### ISSUE THREAD

**Issue by IshtpreetCheema** [haomateach/info1112#11]
Hi, Ishtpreet here, my student id :- 100410466. I have a question that may we can use the web browser for coding for entire course.
Its more convienient as the one which i installed as directed by the videos is not working properly my coding reflects correct in the browser ( C++ Shell ) but not in the code workshop which i have installed.

**Comment by MirsapSaleem** [comment]
Which one did you install? You might've done something wrong bc I followed the video and it work just fine for me :/ 
[C++ Shell](http://www.cpp.sh/) does not shave your work. I think...
I'm using CodeLite and so far it's working great for me :)

**Comment by haomateach** [comment]
@IshtpreetCheema  All browser coding environments nowadays are not complete IDE, which means that you cannot have all the features you need/have in a real IDE, like codelite or visual studio. 

As the first coding for most of you, it's very important to do things "right". Don't choose the easy road, choose the correct one, which is beneficial for you in the long term, including this course.

**Comment by haomateach** [comment]
@IshtpreetCheema  What's your computer? Mac? Windows 10?

**Comment by IshtpreetCheema** [comment]
Am using the windows. No problem I will figure it out as it showing error in the path when it comes to compile

**Comment by haomateach** [comment]
@IshtpreetCheema Closely follow the steps of environment setup. Don't feel frustrated. It's common to experience trial and error during environment setup. Actually, environment setup is always the most painful part :)
