### ISSUE TITLE
Student id: 100405515

### ISSUE THREAD

**Issue by 100405515** [haomateach/info1112#12]
I want to ask that which codelite version we have to install ? Either 14.0.0 or 15.0.0?

**Comment by freela819** [comment]
15.0.0
Generally it should be keep up to date. But my Defender alarmed after download the  latest version. So I did not use 15.0.6

**Comment by haomateach** [comment]
@100405515 It may not be a good idea to use your student id as the post title, the title should be a summary of the question. THanks.
