### ISSUE TITLE
Assignment Instruction

### ISSUE THREAD

**Issue by MirsapSaleem** [haomateach/info1112#15]
100420038

This is how the assignment zip folder should be when I submit it?

https://user-images.githubusercontent.com/90369807/134407951-00d57ec6-3329-4b5f-bbc8-e5123e0eef98.mp4

**Comment by MirsapSaleem** [comment]
Like this?
I deleted all the other stuff and only leave the .cpp file for each question folder.

https://user-images.githubusercontent.com/90369807/134410676-4cba0b46-6767-422e-b765-5509fc56dcd5.mp4

r.

**Comment by haomateach** [comment]
@MirsapSaleem **Please CAREFULLY read the Assignment Instruction and Rubric.pdf.**

Prob 1:  You should name your .cpp file correctly.
Prob 2: The folder only contains .cpp file, and no sub-folders. 

Again, please carefully and patiently read the instruction.

**Comment by MirsapSaleem** [comment]
Ok got it. Thank you!!
