### ISSUE TITLE
CPP files changes into text file after renaming

### ISSUE THREAD

**Issue by Daniel29052** [haomateach/info1112#17]
Hello, I have run into an issue that has changed my CPP files into normal files, this happened right after I renamed the files for hand in. Is there any way of fixing this issue.
![Screenshot 2021-09-28 215950](https://user-images.githubusercontent.com/91583863/135206097-b4337d66-e42f-473e-bd34-9c047fdc4a41.png)

**Comment by haomateach** [comment]
can you right click the file, and select property, and send me the screenshot of the property?

**Comment by Daniel29052** [comment]
![Screenshot 2021-09-28 231315](https://user-images.githubusercontent.com/91583863/135212907-9e0bb0a1-139b-4fc3-8968-62dc73a4ee3d.png)

**Comment by Daniel29052** [comment]
![Screenshot 2021-09-28 231531](https://user-images.githubusercontent.com/91583863/135213165-67d31f4e-97b2-464e-8349-69ab765f90f1.png)

**Comment by haomateach** [comment]
you should add .cpp to the end of the name.

**Comment by Daniel29052** [comment]
Thanks! it worked
