### ISSUE TITLE
Udemy Beginning C++ Programming – From Beginner to Beyond coupon code discount for 2021

### ISSUE THREAD

**Issue by freela819** [haomateach/info1112#2]
I found this on internet and could be used. 
I  think it's not a fraud, but it would be better if someone could check it again.

[https://onlinecoursespro.com/beginning-c-programming-from-beginner-to-beyond-coupon/]

Pei Men, 100395320

**Comment by haomateach** [comment]
It seems that it works. Thanks a lot for sharing!
BTW, make sure that you post your student ID whenever you post an issue here so that the instructor, i.e., I, know who you are. Thanks.

**Comment by haomateach** [comment]
To everyone, this is not a good example of an issue post since a student ID is needed in order for me to know who you are.

**Comment by freela819** [comment]
> who you are

Please call me LeiFeng :wink:
