### ISSUE TITLE
Assignment submission

### ISSUE THREAD

**Issue by 100405515** [haomateach/info1112#20]
100405515.

a)  In folder( with name of student ID), it contains 4 files(.cpp file)? 
b) For each question, there should be one .cpp file means there are total 4 files(.cpp file) in one folder?
c) Inside folder, there should be no subfolders?

**Comment by haomateach** [comment]
All correct !

**Comment by IshtpreetCheema** [comment]
Yeah but am not able to create different cpp files how can we do that can u explain it to me. I wrote answers in just one cpp file

**Comment by MirsapSaleem** [comment]
@IshtpreetCheema 
create and different project file for each of the questions within the workspace folder, after you have done all that and you wrote the codes/answers for each of the questions, navigate to where you have your workspace is saved. for example, I saved my workspace in the Windows (C:)folder (you might have saved your's in a different location idk) so i navigate to the Windows (C:) folder and find my workspace folder. Click on it and you'll see all of your project folders with the name of your projects, double click and you'll see the .cpp files. just copy the .cpp file (and only the .cpp file) and paste it in the folder with the name of your student ID then you can convert it into a zip

I hope this video can help :) sorry, it's a little blurry :/

https://user-images.githubusercontent.com/90369807/135526476-73722004-67af-470d-949d-3d9b7835ca8c.mp4

**Comment by haomateach** [comment]
This works. @MirsapSaleem 
@IshtpreetCheema It's not possible to write all in one single .cpp file. How can one .cpp fle have multiple main() function?
