### ISSUE TITLE
Assignment issue

### ISSUE THREAD

**Issue by 100405515** [haomateach/info1112#23]
100405515.

I have copied only cpp files from my system( where I have saved 4 project files), and then i paste them in new folder (with name of student ID). But, I have not deleted other files from my system. Then it's fine or not?
Sir, when you will open zip folder, and click on .cpp file , then it will open visual studio and my other files will be displayed. It's okay then?

**Comment by haomateach** [comment]
@100405515 Please read the instruction carefully. It says .cpp file only.
