### ISSUE TITLE
assignment issue 

### ISSUE THREAD

**Issue by navleen-kaur** [haomateach/info1112#24]
hey professor! this is Navleen Kaur student ID-100416226. I am having an issue in zipping my files as when I try to zip file it is showing the error when I open .cpp file.
please help me through this!!

**Comment by haomateach** [comment]
Screenshot of the error?

**Comment by haomateach** [comment]
On another topic, your submission file did not meet the requirement, can you please carefully read the assignment instruction and all the announcement and emails I sent regarding this? For example, file name should be your student ID. 

Again, please take my emails and announcement seriously.

**Comment by navleen-kaur** [comment]
![Screenshot (114)](https://user-images.githubusercontent.com/91772772/135726310-840ebfdc-b7d0-4b5e-a4d9-bbc15b91c7e8.png)

**Comment by navleen-kaur** [comment]
also, I have put my .cpp files in  folders as it requires source files too.

**Comment by navleen-kaur** [comment]
hey proffesor I tried making changes if you could see!!
Thank you

**Comment by haomateach** [comment]
Thanks @navleen-kaur

**Comment by haomateach** [comment]
@navleen-kaur With regard to the error, how is "openning the file" related to zipping? Once you zip it, you should unzip it before you open the file. They are two different topics.

**Comment by navleen-kaur** [comment]
I tried submitting my file now could you please check if it does not shows the error

**Comment by haomateach** [comment]
@navleen-kaur  In terms of the format, it looks ok. I won't comment on the actual work.
