### ISSUE TITLE
The requirement of Assignment 2 Question 2 

### ISSUE THREAD

**Issue by tong-victor** [haomateach/info1112#26]
Victor Tong: 100389596
Q2. Modify the program from Q1 so that it also finds the average number of hours per day that a given student studies biology as well as programming. For each given student include two prompts, one for each subject. Have the program print out which subject the student, on average, spent the most time on.

The requirement of this question is not detailed and specific,  so different student may have different understanding. I am wondering whether a sample Run could be provided.

**Comment by haomateach** [comment]
Sample run for Q2 will not be provided as Q1 has been provided. The extra feature of Q2 is that you need to add another dimension, which is subject, to the problem. Each student studies two subjects, biology and programming. 

For example, student 1, studies 2 hours for biology on day 1, 3 hours for biology on day 2, assuming that you have 2 days on the long weekend, then the average hours student 1 spent on studying biology will be 2.5 hours.
