### ISSUE TITLE
Regarding Assignment 2 Question 2

### ISSUE THREAD

**Issue by 100420038** [haomateach/info1112#27]
#100420038

Hello Prof, at the end of question 2 it says "Have the program print out which subject the student, on average, spent the most time on."
Do I just tell it to print out the subject that the student, spent the most time on?
Please see the attached photo bc I'm not sure if I'm on the right track.
Thanks

![q2 sample run](https://user-images.githubusercontent.com/90369807/136712825-373afe16-e2c1-4200-a734-e9c4fda592ec.PNG)

**Comment by haomateach** [comment]
@100420038 Looks good.
