### ISSUE TITLE
development environment

### ISSUE THREAD

**Issue by Sukhmanmalhi05** [haomateach/info1112#3]
CodeLite or Visual Studio and Repl Online C++ Compiler are the same ?

**Comment by haomateach** [comment]
Certainly not. You should install either codelite or Visual Studio in your computer this week. Watch the required videos first. The answer is hidden there. 

@Sukhmanmalhi05  Please make sure that you follow the right format for issue posting.

**Comment by haomateach** [comment]
To everyone, this is not a good example of an issue post since a student ID is needed in order for me to know who you are.
