### ISSUE TITLE
Assignment 2, Question 3

### ISSUE THREAD

**Issue by ZackaryEijbersen** [haomateach/info1112#35]
Student number: 100418273
Hi I was wondering if you could help me with some of the coding for question 3.I have figured out how to do the whole question except, I am not able to figure out how to swap the first and last letter of each word. I have figured out the logic of how to do it, but i am not able to figure out how to actually program it.
I know it has to be a loop that Stores the first letter then seaches for space or end of line, and if it finds a space it stores the varible right behind it(last letter of the word), then starts where it left off and adds the word right in front of the space into a vairable and then reapets untill it reachs the end of the sentece and finds the end of line. If you could can you help me with some of the coding?
Thank you very much Zackary Eijbersen (I have spent considerble time trying to figure this out before I have asked you 11+hours)

**Comment by haomateach** [comment]
@ZackaryEijbersen I suggest that you write everything in pseudo-code first, that helps you to clear up your logic. string class provides so many useful methods. Note that you don't need to create an array here. We MUST use C++ style string, which is much easier than C-style string.

**Comment by haomateach** [comment]
@ZackaryEijbersen Does the following method help?

https://www.cplusplus.com/reference/string/string/substr/

**Comment by needtostayawake** [comment]
100421379
yesss! substr is just what i needed, thank you sir.
