### ISSUE TITLE
Problems with formatting 

### ISSUE THREAD

**Issue by NasirOsman** [haomateach/info1112#37]
student: 100403429
when trying to submit my work the main.CPP changed and now it just says file and not CPP 
![cpp4](https://user-images.githubusercontent.com/90367798/137823281-f665a169-2bef-4cab-9b24-cf14b863512f.PNG)

would this formatting still be correct?

**Comment by haomateach** [comment]
1. Your questions are a bit misleading, since there are NO main.cpp file here at all. 
2. As long as you have added .cpp as the file extension, you don't need to worry about it.

**Comment by NasirOsman** [comment]
I don't know what to do when I change the main.CPP file name so i would have the Q1-student number the cpp file changes into that

**Comment by needtostayawake** [comment]
@NasirOsman copy the main.cpp file from the workspace folder and paste it into another folder, when changing the name, be very careful you don't change the .ccp extension name, just change the name "main".

**Comment by NasirOsman** [comment]
thank you i got it
