### ISSUE TITLE
Problem working in the CodeLite

### ISSUE THREAD

**Issue by ShivanshPatti** [haomateach/info1112#4]
Student ID: 100423299

When I am done with writing down the program on the codelie platform with the "return 0" command. When I press any key so the program keeps on going and the terminal never closes.When I press the enter key "Process completed" message is displayed.

I also tried to change the terminal to the codelite terminal but when I build and run the program  no terminal window pops up.

<img width="1280" alt="Screenshot 2021-09-10 at 1 46 41 AM" src="https://user-images.githubusercontent.com/90420434/132756950-2aca829d-aace-4003-934b-a108466f01cd.png">
<img width="1280" alt="Screenshot 2021-09-10 at 1 46 34 AM" src="https://user-images.githubusercontent.com/90420434/132756956-7f385a0b-8d0b-45c8-9b67-56aaaa25bacb.png">

**Comment by haomateach** [comment]
@ShivanshPatti This is normal with Codelite with Mac. It's ok. You get "My Terminal" displayed. It's good.
