### ISSUE TITLE
ASSIGNMENT 3 Ques 1 

### ISSUE THREAD

**Issue by IshtpreetCheema** [haomateach/info1112#42]
100410466 Ishtpreet
In ques 1, can we put any value of x and y ??

**Comment by haomateach** [comment]
Which assignment?

**Comment by IshtpreetCheema** [comment]
assign 3
about rewriting the function by using pointers

**Comment by IshtpreetCheema** [comment]
in this 1 ques only, after declaring values of x and y then can straight write (cout <<) to show the result or do something else am confused.

**Comment by IshtpreetCheema** [comment]
There is one more question, in order to get the desired result we should convert    {   *   into  &  }  like *a to &a , is it right or not ????
Its regarding the ques 1.
100410466
