### ISSUE TITLE
Codelite Crash

### ISSUE THREAD

**Issue by ShivanshPatti** [haomateach/info1112#43]
Student ID: 100423299

The Codelite Application does not compile the program and I tried to reinstall the Application but now it crashes when ever I try to open it.

I am working on MacOS.

**Comment by haomateach** [comment]
@ShivanshPatti I need more detailed information. Did you follow the steps in the videos regarding installation of codelite on mac os?

At the same time, you can code using online compiler:
https://replit.com/languages/cpp

**Comment by ShivanshPatti** [comment]
I updated the OS of my system and after that these problem started to pop up.
If you have and idea about this problem can you help me.
Thankyou for your help.

**Comment by haomateach** [comment]
Try to install a stable version of codelite. @ShivanshPatti

**Comment by Zuptex** [comment]
@ShivanshPatti I don't have a mac, but I have heard newer mac os don't support 32-bit applications. Try installing a 64-bit version of CodeLite if you haven't already.

**Comment by haomateach** [comment]
@Zuptex Thanks

**Comment by ShivanshPatti** [comment]
> @ShivanshPatti I don't have a mac, but I have heard newer mac os don't support 32-bit applications. Try installing a 64-bit version of CodeLite if you haven't already.

Thankyou so much
