### ISSUE TITLE
Assignment 3 Q3

### ISSUE THREAD

**Issue by ZackaryEijbersen** [haomateach/info1112#44]
100418273

Hi i was trying my program and it keeps giving me a error about my cylinder class? i cnat figure out why. can u help me figure out why?

**Comment by haomateach** [comment]
@ZackaryEijbersen You just posted your solution to a public forum which can lead to plagiarism. Please re-write your code to avoid any potential plagiarism.

If you want to attach the original code, just email me, don't post it here. We talked about this.

**Comment by ZackaryEijbersen** [comment]
100418273
Sorry about that sir i posted this in a hurry just before i went to work. I know that isnt a excuse, and I thank you for reminding me and telling me :)
