### ISSUE TITLE
Assignment 4

### ISSUE THREAD

**Issue by ForbiddenZex** [haomateach/info1112#45]
Hi, I was wondering if there was a sample output picture we could see somewhere to see what the program output is suppose to look like I'm having a hard time visualizing without it.

**Comment by Sandhu5264** [comment]
Ya, I agreed too

**Comment by haomateach** [comment]
@ForbiddenZex @Sandhu5264 For which question?

**Comment by ForbiddenZex** [comment]
@haomateach its got assignment 4 its all 1 question, I was just looking for an example for a final output.

**Comment by haomateach** [comment]
@ForbiddenZex Regarding print function? The print function should print out the required information in a proper way. The output design should be easy and is part of our assignment.

**Comment by ForbiddenZex** [comment]
@haomateach I actually worked it out earlier, I was just confusing myself for no reason.

**Comment by haomateach** [comment]
@ForbiddenZex No worry, it happens.
