### ISSUE TITLE
Code Lite Error

### ISSUE THREAD

**Issue by ZackaryEijbersen** [haomateach/info1112#9]
Student ID:100418273
I was getting some error's when typing in my code, can you tell me why?
![Error C++ code](https://user-images.githubusercontent.com/90363683/133501737-754c1f3f-fb6e-4ee6-8278-364d9377297d.PNG)

**Comment by Zuptex** [comment]
Hello, you put down
std::end1; instead of endl
the 1 is supposed to be an lowercase L

**Comment by ZackaryEijbersen** [comment]
Student ID:100418273 
Thank you :)

**Comment by haomateach** [comment]
@Zuptex  Thanks!
